spring:
  application:
    name: library-gateway
book-rabbitmq:
  exchange: book-direct-exchange
  createRoute: book-create-route
  updateRoute: book-update-route
  deleteRoute: book-delete-rout
book-service:
  url: ${BOOK_SERVICE_URL}